[Air-7] nearplace
peter-house/airbnb-web pull request #10
Opened 2021-03-25 10:52 UTC by grace7937

![image](https://user-images.githubusercontent.com/66059987/112461680-86760800-8da3-11eb-8c33-f1ef808af554.png)

"가까운 여행지 둘러보기" title 추가,
map을 돌려서 총8개의 도시들을 화면에 뿌려줬습니다. 이것은 임시로 만든 배열로된 목데이터 입니다. 추후 서버를 만들어 데이터를 받아올 예정입니다.

2021-03-28 08:56 UTC, livelikeabel commented on src/components/NearPlace.js
> +
불필요한 공백

2021-03-28 08:57 UTC, livelikeabel requested changes

2021-03-28 08:57 UTC, livelikeabel commented on src/components/NearPlace.js
> +
불필요한 공백

2021-03-28 08:57 UTC, livelikeabel commented on src/components/Place.js
> +  const Places = [
Places 데이터를 상위에 두고 map돌면서 Place 컴포넌트를 여러번 렌더해주세요
상수를 선언할 때는 `const PLACES` 가 좀 더 좋은 컨벤션 인거 같아요

2021-03-29 03:34 UTC, grace7937 commented on src/components/Place.js
> +  const Places = [
네! 부모 컨포넌트 NearPlace.js 에서 map을 돌려 Place 컴포넌트를 생성하도록 했습니다.😊

2021-03-29 03:36 UTC, livelikeabel commented on src/components/Place.js
> +  const Places = [
^ 아직 코드 푸시 안한거죠? @grace7937

2021-03-29 03:55 UTC, grace7937 commented on src/components/Place.js
> +  const Places = [
네  map 작업 한곳 더하고 푸쉬 하겠습니다!

2021-03-29 08:38 UTC, livelikeabel commented on src/components/Place.js
> +        {Places.map((place) => {
이거 상위 컴포넌트에서 돌려주세요

2021-03-29 14:13 UTC, livelikeabel approved these changes

2021-03-29 23:59 UTC, merged