[Air- 6] wherever
peter-house/airbnb-web pull request #11
Opened 2021-03-26 02:11 UTC by grace7937

![image](https://user-images.githubusercontent.com/66059987/112566853-17d88f00-8e23-11eb-8b8e-2cfd5718c526.png)

Wherever.js 생성,
WhereverPlace.js 생성,
"어디에서나, 여행은 살아보는거야!" Text 추가 (Wherever.js),
목데이터를 통해서 4개의 박스와 subText를 만들었습니다 (WhereverPlace.js),

Wherever.js 는 component WhereverPlace.js를 return 합니다.

2021-03-28 08:52 UTC, livelikeabel commented on src/components/Banner.js
> +const BannerImg = styled.img `
이거 없어도 될거 같아요! 그냥 img 태그 써주세요

2021-03-28 08:52 UTC, livelikeabel commented on src/components/Banner.js
>  const Banner = () => {
파일 확장자명을 Banner.js가 아닌, Banner.jsx로 해주세요

2021-03-28 08:54 UTC, livelikeabel commented on src/components/Place.js
> +  const Places = [
p1;
이 데이터는 상위 컴포넌트에 두고,
NearPlace에서 map돌면서 Place 컴포넌트를 여러번 렌더 시켜주는게 맞는거 같아요

2021-03-28 08:54 UTC, livelikeabel commented on src/components/Wherever.js
> +
불필요한 공백

2021-03-28 08:55 UTC, livelikeabel commented on src/components/WhereverPlace.js
> +  const WhereverPlaces = [
이것도 데이터 상위 컴포넌트에 두고, map 돌면서 WhereverPlace 컴포넌트를 여러번 렌더해주는걸루!

2021-03-28 08:56 UTC, livelikeabel requested changes
리뷰 적용해주세요!
@grace7937

2021-03-29 03:36 UTC, grace7937 commented on src/components/Banner.js
> +const BannerImg = styled.img `
넵! 그냥 img 태그로 수정했습니다.

2021-03-29 04:18 UTC, grace7937 commented on src/components/Place.js
> +  const Places = [
네 수정 했습니다!

2021-03-29 04:20 UTC, grace7937 commented on src/components/Banner.js
>  const Banner = () => {
jsx로 바꾸니 에러있어서 방법을 찾아보도록 하겠습니다.

2021-03-29 08:37 UTC, livelikeabel commented on src/components/NearPlace.js
> +max-width: 1760px;
indent

2021-03-29 08:37 UTC, livelikeabel commented on src/components/NearPlace.js
> +width: 100%;
indent

2021-03-29 08:37 UTC, livelikeabel commented on src/components/NearPlace.js
> +padding-left: 0px;
indent

2021-03-29 08:37 UTC, livelikeabel commented on src/components/NearPlace.js
> +            <Place/>
indent

2021-03-29 08:38 UTC, livelikeabel approved these changes

2021-03-30 00:00 UTC, merged